name: Auto_Sync OpenWRT Releases

on:
  schedule:
    - cron: '30 23 */8 * *' # Проверка новых релизов
  workflow_dispatch: # Возможность вручную запустить Action

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    outputs:
      release_exists: ${{ steps.check_release.outputs.release_exists }}
      release_tag: ${{ steps.get_release.outputs.release_tag }}
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Get the latest release from OpenWRT
        id: get_release
        run: |
          RELEASE_TAG=$(curl -s https://api.github.com/repos/immortalwrt/immortalwrt/tags | jq -r '.[0].name')
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Check if release exists in your repo
        id: check_release
        run: |
          RELEASE_EXISTS=$(curl -s https://api.github.com/repos/samara15321/awg-immortalwrt/releases/tags/${{ env.release_tag }} | jq -r .tag_name)
          if [ -z "$RELEASE_EXISTS" ] || [ "$RELEASE_EXISTS" == "null" ]; then
            echo "release_exists=false" >> $GITHUB_ENV
          else
            echo "release_exists=true" >> $GITHUB_ENV
          fi

      - name: Проверка сохраненного состояния
        id: check_saved_state
        run: |
          if [ -f saved_release_tag.txt ]; then
            SAVED_RELEASE=$(cat saved_release_tag.txt)
            if [ "$SAVED_RELEASE" == "$RELEASE_TAG" ]; then
              echo "Найдено сохраненное состояние: $SAVED_RELEASE (пропускаем шаги)."
              exit 0
            fi
          fi
       
      - name: Create release in your repo
        if: env.release_exists == 'false'
        run: |
          ART="
          \`\`\`
                   A M N E Z I A   W I R E G U A R D
          -----------------------------------------------------
                   ImmortalWRT ${{ env.release_tag }}
          -----------------------------------------------------
          \`\`\`"
          curl -X POST https://api.github.com/repos/samara15321/awg-immortalwrt/releases \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
                "tag_name": "${{ env.release_tag }}",
                "name": "ImmortalWRT ${{ env.release_tag }}",
                "body": "'"${ART//\"/\\\"}"'"
              }'

  restore-state:
    needs: sync-releases
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка сохраненного состояния
        run: |
          if [ -f saved_release_tag.txt ]; then
            echo "Found saved release state from previous run."
          else
            echo "No saved state found."
          fi
