name: Auto_Sync OpenWRT Releases

on:
  schedule:
    - cron: '30 23 */8 * *'
  workflow_dispatch:

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    outputs:
      release_exists: ${{ steps.check_release.outputs.release_exists }}
      release_tag: ${{ steps.get_release.outputs.release_tag }}
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Get the latest release from OpenWRT
        id: get_release
        run: |
          RELEASE_TAG=$(curl -s https://api.github.com/repos/immortalwrt/immortalwrt/tags | jq -r '.[0].name')
          echo "::set-output name=release_tag::$RELEASE_TAG"

      - name: Check if release exists in your repo
        id: check_release
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/samara15321/awg-immortalwrt/releases/tags/${{ steps.get_release.outputs.release_tag }})
          if [ "$RESPONSE" -eq 200 ]; then
            echo "::set-output name=release_exists::true"
          else
            echo "::set-output name=release_exists::false"
          fi

      - name: Create release in your repo
        if: steps.check_release.outputs.release_exists == 'false'
        run: |
          curl -X POST https://api.github.com/repos/samara15321/awg-immortalwrt/releases \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
          {
            "tag_name": "${{ steps.get_release.outputs.release_tag }}",
            "name": "ImmortalWrt ${{ steps.get_release.outputs.release_tag }}",
            "body": "A M N E Z I A W I R E G U A R D\n--------------------------------------\nImmortalWrt ${{ steps.get_release.outputs.release_tag }}\n--------------------------------------"
          }
          EOF

  run-build:
    needs: sync-releases
    if: needs.sync-releases.outputs.release_exists == 'false'
    uses: samara15321/awg-immortalwrt/.github/workflows/auto_build.yml@master
    with:
      tag_name: ${{ needs.sync-releases.outputs.release_tag }}
